def vendor(request):
    return {
        'ADD_VENDOR' : 'Add Vendor',
        'ACTIVE' : 'Active',
        'INACTIVE' : 'Inactive',
        'CANCEL' : 'Cancel',
        'PERSONAL_INFORMATION' : 'Personal Information',
        'USERNAME' : 'Username',
        'EMAIL' : 'Email',
        'FIRST_NAME' : 'First Name',
        'LAST_NAME' : 'Last Name',
        'ADDRESS_INFORMATION' : 'Address Information',
        'ADDRESS_LINE_1' : 'Address Line 1',
        'ADDRESS_LINE_2' : 'Address Line 2',
        'COUNTRY' : 'Country',
        'STATE' : 'State',
        'CITY' : 'City',
        'PINCODE' : 'Pincode',
        'ADDRESS_TYPE' : 'Address Type',
        'LOGO' : 'Logo',
        'VENDOR_LIST_URL' : 'vendor_list.html',
        'ADD_VENDOR_URL' : 'add_vendor.html',
        'UPDATE_VENDOR_URL' : 'update_vendor.html',
        'VENDOR_DETAILS_URL' : 'vendor_details.html',
        'VENDOR' : 'Vendor',
        'TOTAL_VENDOR' : 'Total Vendor : ',
        'ACTIVE_VENDOR' : 'Active : ',
        'INACTIVE_VENDOR' : 'InActive : ',
        'RESET' : 'Reset',
        'ID' : 'Id',
        'DATE_JOINED' : 'DateJoined',
        'VENDOR_NAME' : 'Vendor Name',
        'STATUS' : 'Status',
        'ACTION' : 'Action',
        'ACCEPT' : 'Accept',
        'REJECT' : 'Reject',
        'EDIT' : 'Edit',
        'DELETE' : 'Delete',
        'UPDATE' : 'Update',
        'VIEW' : 'View',
        'NO_RESULT_MESSAGE' : 'No results found',
        'STATUS' : 'Status',
        'BACK' : 'Back',
        'VENDOR_INFORMATION' : 'Vendor Information...',
        'ADD_SUCCESS_MESSAGE' : "Vendor added Successfully.",
        'UPDATE_VENDOR' : 'Update Vendor',
        'UPDATE_SUCCESS_MESSAGE' : "Vendor Information Updated Successfully.",
        'SEMI_COLON' : ':',
    }
    